server:
  port: 9191
spring:
  datasource:
    url: jdbc:mysql://localhost:4306/bookstore
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: micurug@gmail.com
    password: etofkyluvvhylzbx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
